### ISSUE TITLE
Pagination does not work properly with SqlDataProvider

### ISSUE THREAD

**Issue by stesifrancesco** [kartik-v/yii2-dynagrid#151] opened 2017-03-17 10:48 UTC
I'm tring to use dynagrid with sql data provider.
All seems to wirk properly except pagination, for example if I try to show 5 items for page I got this:

Showing 1-5 of 0 elements (I have 18 elements in my data provider)

Here is my data-provider:
```
` $dataProvider = new SqlDataProvider([
            'sql' =>  $query->createCommand()->getRawSql(),
            'totalCount' => $itemsCount,
            'key' => 'id',
//'pagination' => false, // I tried several configuration for pagination without result
            'sort'=> ['attributes'=>[
                "id",
                "code",
                "name",
                "vat_id",
                "active",
                "customer",
                "supplier",
                "created_at",
                "created_by",
                "parameters"
            ]]
        ]);

            return $dataProvider;
```
One more information: if I use the same DataProvider with simple Grid (without dynagrid I got correctly
Showing 1-5 of 18 elements)

Any idea ?

Thanks in advance for your supports (and many thanks to kartik fro it's wonderful extensions)

Francesco

**Comment by kartik-v** [comment] 2017-04-06 08:33
Cannot reproduce this. 

You must configure `totalCount` property of the SqlDataProvider to the total record count value as highlighted in Yii Docs and you should be able to see that in Dynagrid output (as tested by me separately).

**Comment by kartik-v** [comment] 2017-04-06 08:51
However I am noting an enhancement for other data providers.

**Comment by stesifrancesco** [comment] 2017-04-06 09:18
Hi Kartik and thanks for your answer.
You mean in this way:
$itemsCount = $query->count(); ?
Because I alredy tried in this way without success

**Comment by kartik-v** [comment] 2017-04-06 10:12
Set `dataProvider['totalCount'] = 40` for example and try. That should show total count showing up as `40`. 

Once you tested that - then you need to check how you calculate the total count from your query.

**Comment by stesifrancesco** [comment] 2017-04-06 10:39
dataProvider for what I know is an object, so I alredy tried to set:
   $dataProvider->setTotalCount(40);
either
 $dataProvider = new SqlDataProvider([
            'sql' =>  $query->createCommand()->getRawSql(),
            'totalCount' => 40,
            'key' => 'id',
            'pagination' => [
                'pageSize' => 7
            ],
            'sort'=> ['attributes'=>[
                "id",
                "code",
                "name",
                "vat_id",
                "active",
                "customer",
                "supplier",
                "created_at",
                "created_by",
                "parameters"
            ]]
        ]);

Without success....(showin 1-10 of  elements)

As I wrote this issue is only with dynagrid.
With your grid and with the same data provider all work without problems.

**Comment by kartik-v** [comment] 2017-04-06 18:55
This is resolved via this [mega commit for updates to release v1.4.5](https://github.com/kartik-v/yii2-dynagrid/commit/13e013ffcde9ef7f99b7d2ab0ee2b91e437abbea).

**Closed by kartik-v** 2017-04-06 18:55 UTC
Labels: enhancement

**Comment by stesifrancesco** [comment] 2017-04-06 20:37
Now It works fine: Thanks a lot !
